version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "semihkeskindev"
    assignees:
      - "semihkeskindev"
    labels:
      - "dependabot"
      - "github-actions"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[gha] - upgrade github action dependencies"
      include: "scope"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "semihkeskindev"
    assignees:
      - "semihkeskindev"
    labels:
      - "dependabot"
      - "composer"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[composer] - upgrade composer dependencies"
      include: "scope"